/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import n.queens.problem.FitnessEnum;
import javax.swing.DefaultComboBoxModel;
import metaheuristics.SimulatingAnnealing;
import metaheuristics.TabuSearch;

/**
 *
 * @author yannick
 */
public class MainWindow extends javax.swing.JFrame
{

    /**
     * Creates new form MainWindow
     */
    public MainWindow()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        chessSizeLabel = new javax.swing.JLabel();
        chessSizeField = new javax.swing.JTextField();
        methodPane = new javax.swing.JTabbedPane();
        annealingPanel = new javax.swing.JPanel();
        simuAnnealingLabel = new javax.swing.JLabel();
        maxIterationsAnnealingLabel = new javax.swing.JLabel();
        maxIterationsAnnealingField = new javax.swing.JTextField();
        temperatureThresholdLabel = new javax.swing.JLabel();
        temperatureThresholdField = new javax.swing.JTextField();
        temperatureVariationMulLabel = new javax.swing.JLabel();
        temperatureVariationMulField = new javax.swing.JTextField();
        fitnessAnnealingChooseLabel = new javax.swing.JLabel();
        fitnessAnnealingComboBox = new javax.swing.JComboBox<>();
        runAnnealing = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tabuSearchLabel = new javax.swing.JLabel();
        maxIterationsTabuLabel = new javax.swing.JLabel();
        maxIterationsTabuField = new javax.swing.JTextField();
        tabuListSizeField = new javax.swing.JTextField();
        tabuListSizeLabel = new javax.swing.JLabel();
        fitnessChooseTabuLabel = new javax.swing.JLabel();
        fitnessComboBox1 = new javax.swing.JComboBox<>();
        runTabu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("N Queens problem");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        chessSizeLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        chessSizeLabel.setText("Size of the chessboard (= queens number)");

        chessSizeField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        chessSizeField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        chessSizeField.setToolTipText("i.e. 8");
        chessSizeField.setMinimumSize(new java.awt.Dimension(4, 30));
        chessSizeField.setPreferredSize(new java.awt.Dimension(4, 30));

        simuAnnealingLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        simuAnnealingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simuAnnealingLabel.setText("Simulated Annealing");

        maxIterationsAnnealingLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        maxIterationsAnnealingLabel.setText("Max number of iterations");
        maxIterationsAnnealingLabel.setMaximumSize(new java.awt.Dimension(170, 30));
        maxIterationsAnnealingLabel.setMinimumSize(new java.awt.Dimension(170, 30));

        maxIterationsAnnealingField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        maxIterationsAnnealingField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        maxIterationsAnnealingField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                maxIterationsAnnealingFieldActionPerformed(evt);
            }
        });

        temperatureThresholdLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        temperatureThresholdLabel.setText("Temperature stopping threshold");
        temperatureThresholdLabel.setMaximumSize(new java.awt.Dimension(225, 30));
        temperatureThresholdLabel.setMinimumSize(new java.awt.Dimension(225, 30));
        temperatureThresholdLabel.setPreferredSize(new java.awt.Dimension(225, 30));

        temperatureThresholdField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        temperatureThresholdField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        temperatureThresholdField.setToolTipText("");

        temperatureVariationMulLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        temperatureVariationMulLabel.setText("Temperature variation multiplier");
        temperatureVariationMulLabel.setMaximumSize(new java.awt.Dimension(217, 30));
        temperatureVariationMulLabel.setMinimumSize(new java.awt.Dimension(217, 30));
        temperatureVariationMulLabel.setPreferredSize(new java.awt.Dimension(217, 30));

        temperatureVariationMulField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        temperatureVariationMulField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        temperatureVariationMulField.setMinimumSize(new java.awt.Dimension(4, 30));
        temperatureVariationMulField.setPreferredSize(new java.awt.Dimension(78, 30));

        fitnessAnnealingChooseLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fitnessAnnealingChooseLabel.setText("Fitness type");

        fitnessAnnealingComboBox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fitnessAnnealingComboBox.setModel(new DefaultComboBoxModel<>(FitnessEnum.values()));

        runAnnealing.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        runAnnealing.setText("RUN MATE");
        runAnnealing.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                runAnnealingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout annealingPanelLayout = new javax.swing.GroupLayout(annealingPanel);
        annealingPanel.setLayout(annealingPanelLayout);
        annealingPanelLayout.setHorizontalGroup(
            annealingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annealingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(annealingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temperatureThresholdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperatureVariationMulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fitnessAnnealingChooseLabel)
                    .addComponent(maxIterationsAnnealingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(annealingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(temperatureThresholdField)
                    .addComponent(temperatureVariationMulField, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(maxIterationsAnnealingField)
                    .addComponent(fitnessAnnealingComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(annealingPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(runAnnealing)))
                .addContainerGap(359, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, annealingPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(simuAnnealingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
        );
        annealingPanelLayout.setVerticalGroup(
            annealingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annealingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simuAnnealingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(annealingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxIterationsAnnealingField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxIterationsAnnealingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(annealingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temperatureThresholdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperatureThresholdField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(annealingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temperatureVariationMulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperatureVariationMulField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(annealingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fitnessAnnealingChooseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fitnessAnnealingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runAnnealing)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        maxIterationsAnnealingField.setText(Integer.toString(SimulatingAnnealing.MAX_ITERATIONS));
        temperatureThresholdField.setText(Float.toString(SimulatingAnnealing.TEMPERATURE_STROPPING_THRESHOLD));
        temperatureVariationMulField.setText(Float.toString(SimulatingAnnealing.TEMPRATURE_VARIATION_MULTIPLIER));
        fitnessAnnealingComboBox.setSelectedItem(SimulatingAnnealing.FITNESS_TYPE);

        methodPane.addTab("Simulated Annealing", annealingPanel);

        tabuSearchLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tabuSearchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tabuSearchLabel.setText("Tabu Search");

        maxIterationsTabuLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        maxIterationsTabuLabel.setText("Max number of iterations");
        maxIterationsTabuLabel.setMaximumSize(new java.awt.Dimension(170, 30));
        maxIterationsTabuLabel.setMinimumSize(new java.awt.Dimension(170, 30));

        maxIterationsTabuField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        maxIterationsTabuField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        maxIterationsTabuField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                maxIterationsTabuFieldActionPerformed(evt);
            }
        });

        tabuListSizeField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tabuListSizeField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tabuListSizeField.setToolTipText("");

        tabuListSizeLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tabuListSizeLabel.setText("Size of the tabu list");
        tabuListSizeLabel.setMaximumSize(new java.awt.Dimension(225, 30));
        tabuListSizeLabel.setMinimumSize(new java.awt.Dimension(225, 30));
        tabuListSizeLabel.setPreferredSize(new java.awt.Dimension(225, 30));

        fitnessChooseTabuLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fitnessChooseTabuLabel.setText("Fitness type");

        fitnessComboBox1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fitnessComboBox1.setModel(new DefaultComboBoxModel<>(FitnessEnum.values()));

        runTabu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        runTabu.setText("RUN MATE");
        runTabu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                runTabuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(tabuSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabuListSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fitnessChooseTabuLabel)
                    .addComponent(maxIterationsTabuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(runTabu))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tabuListSizeField)
                        .addComponent(maxIterationsTabuField)
                        .addComponent(fitnessComboBox1, 0, 135, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabuSearchLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxIterationsTabuField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxIterationsTabuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tabuListSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabuListSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fitnessChooseTabuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fitnessComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runTabu)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        maxIterationsTabuField.setText(Integer.toString(TabuSearch.MAX_ITERATIONS));
        tabuListSizeField.setText(Integer.toString(TabuSearch.TABU_LIST_SIZE));
        fitnessAnnealingComboBox.setSelectedItem(SimulatingAnnealing.FITNESS_TYPE);

        methodPane.addTab("Tabu Search", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        methodPane.addTab("Genetic Algorithm", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(methodPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chessSizeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chessSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chessSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chessSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(methodPane)
                .addContainerGap())
        );

        chessSizeField.setText(Integer.toString(8));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maxIterationsAnnealingFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_maxIterationsAnnealingFieldActionPerformed
    {//GEN-HEADEREND:event_maxIterationsAnnealingFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxIterationsAnnealingFieldActionPerformed

    private void runAnnealingActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_runAnnealingActionPerformed
    {//GEN-HEADEREND:event_runAnnealingActionPerformed
        SimulatingAnnealing.execute(Integer.parseInt(this.chessSizeField.getText()), Integer.parseInt(this.maxIterationsAnnealingField.getText()),
                Float.parseFloat(this.temperatureThresholdField.getText()), Float.parseFloat(this.temperatureVariationMulField.getText()), (FitnessEnum)this.fitnessAnnealingComboBox.getSelectedItem());
    }//GEN-LAST:event_runAnnealingActionPerformed

    private void maxIterationsTabuFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_maxIterationsTabuFieldActionPerformed
    {//GEN-HEADEREND:event_maxIterationsTabuFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxIterationsTabuFieldActionPerformed

    private void runTabuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_runTabuActionPerformed
    {//GEN-HEADEREND:event_runTabuActionPerformed
        TabuSearch.execute(Integer.parseInt(this.chessSizeField.getText()), Integer.parseInt(this.tabuListSizeField.getText()),
                Integer.parseInt(this.maxIterationsAnnealingField.getText()), (FitnessEnum)this.fitnessAnnealingComboBox.getSelectedItem());
    }//GEN-LAST:event_runTabuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel annealingPanel;
    private javax.swing.JTextField chessSizeField;
    private javax.swing.JLabel chessSizeLabel;
    private javax.swing.JLabel fitnessAnnealingChooseLabel;
    private javax.swing.JComboBox<FitnessEnum> fitnessAnnealingComboBox;
    private javax.swing.JLabel fitnessChooseTabuLabel;
    private javax.swing.JComboBox<FitnessEnum> fitnessComboBox1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField maxIterationsAnnealingField;
    private javax.swing.JLabel maxIterationsAnnealingLabel;
    private javax.swing.JTextField maxIterationsTabuField;
    private javax.swing.JLabel maxIterationsTabuLabel;
    private javax.swing.JTabbedPane methodPane;
    private javax.swing.JButton runAnnealing;
    private javax.swing.JButton runTabu;
    private javax.swing.JLabel simuAnnealingLabel;
    private javax.swing.JTextField tabuListSizeField;
    private javax.swing.JLabel tabuListSizeLabel;
    private javax.swing.JLabel tabuSearchLabel;
    private javax.swing.JTextField temperatureThresholdField;
    private javax.swing.JLabel temperatureThresholdLabel;
    private javax.swing.JTextField temperatureVariationMulField;
    private javax.swing.JLabel temperatureVariationMulLabel;
    // End of variables declaration//GEN-END:variables
}
